[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
identity_registry = "4ZVLebPiji6XZ1H2Tb7AhjA6ZgMU7JrTWDRoBPMyS8Zn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
